export const REGISTER_AS_CONFIG_NAMES = {
  USERS_SERVICE: 'USERS_SERVICE',
  USERS_REPOSITORY: 'USERS_REPOSITORY',
  USERS_MODEL: 'USERS_MODEL',
  USERS_MODULE: 'USERS_MODULE',
  DATABASE: 'DATABASE',
};
